### PR TITLE
Update provider.ts

### PR DESCRIPTION
**Pull request by vitaly-t**
You were creating an empty-result `SET` stuff, which assigned columns to themselves, whereas you are supposed to assign values from the `EXCLUDED` table.

### CODE REVIEW

**Comment by vitaly-t** [comment]
Check out this - https://stackoverflow.com/questions/63327528/insert-on-conflict-do-update-using-pg-promise-helpers-for-multi-row-insert-updat

**Comment by rolandreads** [comment]
Thanks, assigning from excluded is obviously better approach, but I'm still trying to catch on why `const setQuery = this.pgp.helpers.sets(updateData, cs);` did not work 

btw, could you recommend anything that would enable me to use pg-promise in serverless environment?  I'm looking for anything that plays nicely with functions and does not max out connections in case of thousands of invocations

**Comment by vitaly-t** [comment]
It might work sometimes, but is the wrong approach, because for one thing, [sets](https://vitaly-t.github.io/pg-promise/helpers.html#.sets) accounts for the `ColumnSet` attributes on columns, which you do not want in this case, and for another - you are creating an extra value-formatting layer, instead of just using already in-server values created by Postgres within its temporary `excluded` table (created specially for this).

**Comment by vitaly-t** [comment]
>  that would enable me to use pg-promise in serverless environment

Check out this issue - https://github.com/vitaly-t/pg-promise/issues/743

Not sure if that even works, I never looked into that up close.

**Comment by rolandreads** [comment]
I did, emulating database is not what I'm after, anyways, thanks for all the information and knowledge you shared :)

**Pull request merged**
